[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["audio_bench"]

[project]
name = "audiobench"
version = "0.1.0"
description = "Benchmark for evaluating Audio Large Language Models"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "plotly",
    "kaleido",
    "fire",
    "transformers",
    "evaluate",
    "datasets<4",
    "jiwer<4",
    "more-itertools",
    "huggingface-hub",
    "librosa",
    "soundfile",
]

[project.optional-dependencies]
vllm = ["vllm>=0.8.5"]
api = ["google-generativeai", "openai"]
math = ["latex2sympy2"]
kimi = ["kimi-audio @ git+https://github.com/MoonshotAI/Kimi-Audio.git"]
flow-judge = ["flow-judge"]
qwen-omni = ["qwen-omni-utils"]
plot = ["playwright"]
all = [
    "audiobench[vllm,api,math,kimi,flow-judge,qwen-omni,plot]",
]
