global:
  batch_size: 1
  overwrite: false
  number_of_samples: 5
  skip_errors: False
  
  datasets:
    # speech
    - name: Air_Bench_Chat_spokenwoz
      path: blabla/speechlm_benchmark/nemo/misc/en/context/AIR_bench/Chat/speech/spokenwoz/test.jsonl
      metrics: linagora_api_oss120
      language: en
      task: aqa
    - name: Air_Bench_Foundation_meld
      path: blabla/speechlm_benchmark/nemo/misc/en/context/AIR_bench/Foundation/speech/meld/test.jsonl
      metrics: linagora_api_oss120 
      language: en
      task: aqa

models:
  - name: canary_qwen
  - name: luciole_audio
