global:
  batch_size: 25
  overwrite: False
  number_of_samples: 1000
  skip_errors: False
  backend: vllm
  
  datasets:
    # ASR - FR
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/fr/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/fr/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: Multilingual_LibriSpeech
      path: <DATA_DIR>/nemo/asr/fr/context/Multilingual_LibriSpeech/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/fr/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: VoxPopuli
      path: <DATA_DIR>/nemo/asr/fr/context/VoxPopuli/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: SUMM-RE
      path: <DATA_DIR>/nemo/asr/fr/context/SUMM-RE/test.jsonl
      metrics: wer
      task: asr
      language: fr
    - name: YouTubeFr
      path: <DATA_DIR>/nemo/asr/fr/context/YouTubeFr/test_split6.jsonl
      metrics: wer
      task: asr
      language: fr
    # ASR - EN
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/en/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: en
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/en/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: en
    - name: Multilingual_LibriSpeech
      path: <DATA_DIR>/nemo/asr/en/context/Multilingual_LibriSpeech/test.jsonl
      metrics: wer
      task: asr
      language: en
    - name: VoxPopuli
      path: <DATA_DIR>/nemo/asr/en/context/VoxPopuli/test.jsonl
      metrics: wer
      task: asr
      language: en
    # ASR - IT
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/it/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: it
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/it/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: it
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/it/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: it
    # ASR - DE
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/de/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: de
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/de/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: de
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/de/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: de
    # ASR - NL
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/nl/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: nl
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/nl/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: nl
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/nl/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: nl
    # ASR - ES
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/es/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: es
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/es/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: es
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/es/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: es
    # ASR - PT
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/pt/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: pt
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/pt/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: pt
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/pt/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: pt
    # ASR - AR
    - name: Fleurs
      path: <DATA_DIR>/nemo/asr/ar/context/FLEURS/test.jsonl
      metrics: wer
      task: asr
      language: ar
    - name: CommonVoice
      path: <DATA_DIR>/nemo/asr/ar/context/CommonVoice/test.jsonl
      metrics: wer
      task: asr
      language: ar
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/asr/ar/context/Multilingual_TEDx/test.jsonl
      metrics: wer
      task: asr
      language: ar
    # AST
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/ast/fr-en/context/Multilingual_TEDx/test.jsonl
      metrics: bleu
      task: ast
      language: fr-en
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/ast/fr-es/context/Multilingual_TEDx/test.jsonl
      metrics: bleu
      task: ast
      language: fr-es
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/ast/es-fr/context/Multilingual_TEDx/test.jsonl
      metrics: bleu
      task: ast
      language: es-fr
    - name: Multilingual_TEDx
      path: <DATA_DIR>/nemo/ast/es-it/context/Multilingual_TEDx/test.jsonl
      metrics: bleu
      task: ast
      language: es-it

models:
  - name: luciole_audio_canary_qwen3_1b_v2
    path: <MODELS_DIR>/Canary-Qwen3-1.7B-v2
  # - name: canary_qwen           # ASR only
  # - name: seallms_audio_7b      # south east asia model
  - name: qwen2_omni_3b
  # - name: qwen2_omni_7b         # Do we need the 3 Qwen?
  - name: qwen2_audio_7b_instruct
  - name: phi_4_multimodal_instruct
  - name: audio_flamingo_3        # need very recent vLLM (and so transformers)
  - name: salmonn_7b              # transformers only
  - name: voxtral_mini_3b_2507    # transformers only
  - name: kimi_audio_7b_instruct  # transformers only - very slow
