global:
  batch_size: 25
  overwrite: False
  number_of_samples: 500
  skip_errors: False
  backend: vllm
  gpu_memory_utilization: 0.4
  compute_metrics: True
  skip_inference: False

  datasets:
    # ASR
    - group: asr
      metrics: wer
      task: asr
      min_audio_duration: 1
      max_audio_duration: 30
      datasets:
        - group: asr_fr
          language: fr
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/fr/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/fr/context/CommonVoice/test.jsonl
            - name: Multilingual_LibriSpeech
              path: <DATA_DIR>/nemo/asr/fr/context/Multilingual_LibriSpeech/test.jsonl
              ignore_offsets: true
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/fr/context/Multilingual_TEDx/test.jsonl
            - name: VoxPopuli
              path: <DATA_DIR>/nemo/asr/fr/context/VoxPopuli/test.jsonl
            - name: SUMM-RE
              path: <DATA_DIR>/nemo/asr/fr/context/SUMM-RE/test.jsonl
              min_audio_duration: 2
            - name: YouTubeFr
              path: <DATA_DIR>/nemo/asr/fr/context/YouTubeFr/test_split6.jsonl

        - group: asr_en
          language: en
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/en/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/en/context/CommonVoice/test.jsonl
            - name: Multilingual_LibriSpeech
              path: <DATA_DIR>/nemo/asr/en/context/Multilingual_LibriSpeech/test.jsonl
              ignore_offsets: true
            - name: VoxPopuli
              path: <DATA_DIR>/nemo/asr/en/context/VoxPopuli/test.jsonl

        - group: asr_it
          language: it
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/it/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/it/context/CommonVoice/test.jsonl
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/it/context/Multilingual_TEDx/test.jsonl

        - group: asr_de
          language: de
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/de/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/de/context/CommonVoice/test.jsonl
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/de/context/Multilingual_TEDx/test.jsonl

        - group: asr_nl
          language: nl
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/nl/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/nl/context/CommonVoice/test.jsonl

        - group: asr_es
          language: es
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/es/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/es/context/CommonVoice/test.jsonl
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/es/context/Multilingual_TEDx/test.jsonl

        - group: asr_pt
          language: pt
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/pt/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/pt/context/CommonVoice/test.jsonl
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/pt/context/Multilingual_TEDx/test.jsonl

        - group: asr_ar
          language: ar
          datasets:
            - name: Fleurs
              path: <DATA_DIR>/nemo/asr/ar/context/FLEURS/test.jsonl
            - name: CommonVoice
              path: <DATA_DIR>/nemo/asr/ar/context/CommonVoice/test.jsonl
            - name: Multilingual_TEDx
              path: <DATA_DIR>/nemo/asr/ar/context/Multilingual_TEDx/test.jsonl

    # AST
    - group: ast
      metrics: [bleu, meteor]
      task: ast
      min_audio_duration: 1
      max_audio_duration: 30
      datasets:
        - name: Multilingual_TEDx
          path: <DATA_DIR>/nemo/ast/fr-en/context/Multilingual_TEDx/test.jsonl
          language: fr-en
        - name: Multilingual_TEDx
          path: <DATA_DIR>/nemo/ast/fr-es/context/Multilingual_TEDx/test.jsonl
          language: fr-es
        - name: Multilingual_TEDx
          path: <DATA_DIR>/nemo/ast/es-fr/context/Multilingual_TEDx/test.jsonl
          language: es-fr
        - name: Multilingual_TEDx
          path: <DATA_DIR>/nemo/ast/es-it/context/Multilingual_TEDx/test.jsonl
          language: es-it

    # Spoken Question Answering
    - group: sqa
      metrics: flow_judge
      task: Question Answering
      sub_task: QA
      datasets:
        - group: sqa_fr
          language: fr
          datasets:
            - name: VoxPopuli-QA
              path: <DATA_DIR>/nemo/question-answering/qa_audio-context-text-question/fr/VoxPopuli-QA/test.jsonl
            - name: CohereLabs-Aya_collection
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/CohereLabs--aya_collection/test.jsonl
            - name: ComparIA
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/ComparIA/test.jsonl
            - name: Vigogne--Alpaca
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/Vigogne--Alpaca/test.jsonl

        - group: sqa_en
          language: en
          datasets:
            - name: cn_college_listen_mcq_test
            - name: slue_p2_sqa5_test
            - name: dream_tts_mcq_test
            - name: public_sg_speech_qa_test
            - name: spoken_squad_test
            - name: VoxPopuli-QA
              path: <DATA_DIR>/nemo/question-answering/qa_audio-context-text-question/en/VoxPopuli-QA/test.jsonl
            - name: multitask_SQA
              path: <DATA_DIR>/nemo/misc/en/context/AudioLLMs--Multitask-National-Speech-Corpus-v1-extend/SQA/test.jsonl
            - name: AIR_bench_Chat_fisher
              path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Chat/speech/fisher/test.jsonl
            - name: AIR_bench_Chat_spokenwoz
              path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Chat/speech/spokenwoz/test.jsonl
            # - name: ContextDialog
            #   path: <DATA_DIR>/nemo/question-answering/qa_audio-question-text-context/en/ContextDialog/test.jsonl
            # - name: HeySQuAD_human
            #   path: <DATA_DIR>/nemo/question-answering/qa_audio-question-text-context/en/yijingwu--HeySQuAD_human/test.jsonl
            # - name: MELD_AcousticDS
            #   path: <DATA_DIR>/nemo/misc/en/context/MELD/AcousticDS/test.jsonl
    # Math Question Answering
    - group: math_qa
      metrics: acc
      task: Math Question Answering
      language: en
      datasets:
        - name: spoken-mqa_short_digit
        - name: spoken-mqa_long_digit
        - name: spoken-mqa_single_step_reasoning
        - name: spoken-mqa_multi_step_reasoning

    # Dialogue Summarization
    - group: dialogue_summarization
      metrics: flow_judge
      task: Dialogue Summarization
      language: en
      datasets:
        - name: multitask_SDS
          path: <DATA_DIR>/nemo/misc/en/context/AudioLLMs--Multitask-National-Speech-Corpus-v1-extend/SDS/test.jsonl

    # Instruction Following
    - group: instruction_following
      metrics: flow_judge
      task: Instruction Following
      sub_task: Spoken Instruction
      datasets:
        - group: instruction_following_fr
          language: fr
          datasets:
            - name: CohereLabs-Aya_collection
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/CohereLabs--aya_collection/test.jsonl
            - name: ComparIA
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/ComparIA/test.jsonl
            - name: Vigogne--Alpaca
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/fr/Vigogne--Alpaca/test.jsonl

        - group: instruction_following_en
          language: en
          datasets:
            - name: alpaca_audio_test
            - name: openhermes_audio_test
            - name: Fixie-ai--oo-gpt4-200k-audio
              path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/en/fixie-ai--oo-gpt4-200k-audio/test.jsonl
            # - name: JST-SUPERB--NMSQA-test-gpt4
            #   path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/en/JST-SUPERB--NMSQA-test-gpt4/test.jsonl
            # - name: UltraChat-300K-SLAM-Omni
            #   path: <DATA_DIR>/nemo/question-answering/qa_audio-question-only/en/worstchan--UltraChat-300K-SLAM-Omni/test_updated.jsonl

    # Audio Question Answering
    - group: audio_qa
      metrics: flow_judge
      task: Audio Question Answering
      language: en
      datasets:
        - name: clotho_aqa_test
        - name: wavcaps_qa_test
        - name: audiocaps_qa_test
        - name: AIR_bench_Chat-audiocaps_cv
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Chat/mixed/audiocaps_cv/test.jsonl
        - name: AIR_bench_Chat-musiccaps_cv
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Chat/mixed/musiccaps_cv/test.jsonl
        - name: AIR_bench_Foundation_TUT2017
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/sound/TUT2017/test.jsonl

    # Audio Captioning
    - group: audio_captioning
      metrics: flow_judge
      task: Audio Captioning
      language: en
      datasets:
        - name: wavcaps_test
        - name: audiocaps_test

    # Emotion Recognition
    - group: emotion_recognition
      metrics: flow_judge
      task: Emotion Recognition
      sub_task: Emotion
      datasets:
        - group: emotion_recognition_fr
          language: fr
          datasets:
            - name: MELD_EmotionDS
              path: <DATA_DIR>/nemo/misc/fr/context/MELD/EmotionDS/test.jsonl
            - name: Ssi-speech-emotion-recognition
              path: <DATA_DIR>/nemo/misc/fr/context/ssi-speech-emotion-recognition/test.jsonl

        - group: emotion_recognition_en
          language: en
          datasets:
            - name: iemocap_emotion_test
            # - name: meld_sentiment_test
            # - name: meld_emotion_test
            - name: Ssi-speech-emotion-recognition
              path: <DATA_DIR>/nemo/misc/en/context/ssi-speech-emotion-recognition/test.jsonl
            - name: MELD_EmotionDS
              path: <DATA_DIR>/nemo/misc/en/context/MELD/EmotionDS/test.jsonl

    # Accent Recognition
    - group: accent_recognition
      metrics: flow_judge
      task: Accent Recognition
      language: en
      datasets:
        - name: voxceleb_accent_test
        # - name: imda_ar_sentence
        # - name: imda_ar_dialogue

    # Gender Recognition
    - group: gender_recognition
      metrics: flow_judge
      task: Gender Recognition
      datasets:
        - group: gender_recognition_fr
          language: fr
          datasets:
            - name: CommonVoice_Age-Gender_reco
              path: <DATA_DIR>/nemo/misc/fr/context/CommonVoice_Age-Gender_reco/test.jsonl

        - group: gender_recognition_en
          language: en
          datasets:
            - name: iemocap_gender_test
            # - name: voxceleb_gender_test
            - name: CommonVoice_Age-Gender_reco
              path: <DATA_DIR>/nemo/misc/en/context/CommonVoice_Age-Gender_reco/test.jsonl

    # Music Question Answering
    - group: music_qa
      metrics: flow_judge
      task: Music Question Answering
      language: en
      datasets:
        - name: muchomusic_test
        - name: AIR_bench_Foundation_MUSIC-AVQA
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/music/music_avqa/test.jsonl

    # Music Understanding
    - group: music_understanding
      metrics: flow_judge
      task: Music Understanding
      language: en
      datasets:
        - name: AIR_bench_Foundation_NSynth
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/music/nsynth/test.jsonl
        - name: AIR_bench_Foundation_MTJ-Jamendo
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/music/MTJ-Jamendo/test.jsonl
        - name: AIR_bench_Foundation_FMA
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/music/fma/test.jsonl
    # Music Captioning
    - group: music_captioning
      metrics: flow_judge
      task: Music Captioning
      language: en
      datasets:
        - name: MusicCaps
          path: <DATA_DIR>/nemo/music/music-captioning/en/context/MusicCaps/test.jsonl

    # Spoken Language Identification
    - group: language_identification
      metrics: flow_judge
      task: Spoken Language Identification
      language: en
      datasets:
        - name: AIR_bench_Foundation_covost2
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/speech/covost2/test.jsonl

    # Speaker Verification
    - group: speaker_verification
      metrics: flow_judge
      task: Speaker Verification
      language: en
      datasets:
        - name: AIR_bench_Foundation_voxceleb
          path: <DATA_DIR>/nemo/misc/en/context/AIR_bench/Foundation/speech/voxceleb1/test.jsonl

    # Stress Test
    - group: stress_test
      metrics: flow_judge
      task: Stress Test
      datasets:
        - group: stress_test_fr
          language: fr
          datasets:
            - name: Stress_SSD
              path: <DATA_DIR>/nemo/misc/fr/context/Stress/ssd/test.jsonl
              sub_task: SSD

        - group: stress_test_en
          language: en
          datasets:
            - name: Stress_SSD
              path: <DATA_DIR>/nemo/misc/en/context/Stress/ssd/test.jsonl
              sub_task: SSD
            - name: Stress_SSR
              path: <DATA_DIR>/nemo/misc/en/context/Stress/ssr/test.jsonl
              sub_task: SSR

models:
  - name: luciole_audio_canary_qwen3_1b_v2
    path: <MODELS_DIR>/Canary-Qwen3-1.7B-v2
  # - name: canary_qwen           # ASR only
  # - name: seallms_audio_7b      # south east asia model
  - name: qwen2_omni_3b
  # - name: qwen2_omni_7b         # Do we need the 3 Qwen?
  - name: qwen2_audio_7b_instruct
    batch_size: 25
  - name: phi_4_multimodal_instruct
  - name: voxtral_mini_3b_2507
  # - name: audio_flamingo_3        # need very recent vLLM (and so transformers)
  #   batch_size: 25
  # - name: salmonn_7b              # transformers only - very slow
  #   batch_size: 1
  - name: kimi_audio_7b_instruct  # transformers only - very slow
    batch_size: 1