global:
  batch_size: 1
  overwrite: false
  number_of_samples: 5
  skip_errors: False
  
  datasets:
    - name: librispeech_test_clean
      metrics: wer
      number_of_samples: 10

models:
  - name: luciole_audio
  - name: canary_qwen
  - name: qwen2-audio-7b-instruct
    backend: vllm